// <auto-generated />
using System;
using DeliveryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241028170040_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryService.Models.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("Guid")
                        .HasColumnName("id");

                    b.Property<int>("Courer_Id")
                        .HasColumnType("integer")
                        .HasColumnName("Courer_Id");

                    b.Property<DateTime>("Delivery_Time")
                        .HasColumnType("DateTime")
                        .HasColumnName("Delivery_Time");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order_Id")
                        .HasColumnType("integer")
                        .HasColumnName("Order_Id");

                    b.Property<string>("Shipping_Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("string")
                        .HasColumnName("Shipping_Address");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("decimal")
                        .HasColumnName("Total_Price");

                    b.HasKey("Id")
                        .HasName("PK_Delivery");

                    b.ToTable("Delivery", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
