name: ci

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/s3ng.sln

      - name: Build project
        run: dotnet build src/s3ng.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/Tests/UserService.Test/Application/UserService.Application.Test/UserService.Application.Test.csproj